/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cbsquiz;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author emirh
 */
public class shapeMaker extends javax.swing.JFrame {

    /**
     * Creates new form shapeMaker
     */
    ArrayList<Integer> xCoordinateList = new ArrayList<Integer>();
    ArrayList<Integer> yCoordinateList = new ArrayList<Integer>();
    drawings d = new drawings();
    public shapeMaker() {
        initComponents();
        nKucukCheck.setVisible(false);
        nOrtaCheck.setVisible(false);
        nBuyukCheck.setVisible(false);
        cInceCheck.setVisible(false);
        cOrtaCheck.setVisible(false);
        cKalınCheck.setVisible(false);
        bosCheck.setVisible(false);
        doluCheck.setVisible(false);
        taraliCheck.setVisible(false);
        xCoordinate.setVisible(false);
        yCoordinate.setVisible(false);
        xCoordinateLabel.setVisible(false);
        yCoordinateLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noktaCheck = new javax.swing.JCheckBox();
        nOrtaCheck = new javax.swing.JCheckBox();
        nKucukCheck = new javax.swing.JCheckBox();
        nBuyukCheck = new javax.swing.JCheckBox();
        cizgiCheck = new javax.swing.JCheckBox();
        cInceCheck = new javax.swing.JCheckBox();
        cOrtaCheck = new javax.swing.JCheckBox();
        cKalınCheck = new javax.swing.JCheckBox();
        polyCheck = new javax.swing.JCheckBox();
        bosCheck = new javax.swing.JCheckBox();
        doluCheck = new javax.swing.JCheckBox();
        taraliCheck = new javax.swing.JCheckBox();
        ekleButton = new javax.swing.JButton();
        xCoordinate = new javax.swing.JTextField();
        yCoordinate = new javax.swing.JTextField();
        xCoordinateLabel = new javax.swing.JLabel();
        yCoordinateLabel = new javax.swing.JLabel();
        makeItHappenBoiii = new javax.swing.JButton();
        widthText = new javax.swing.JTextField();
        heightText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cizButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shapes, dots & lines");
        setBackground(new java.awt.Color(204, 52, 227));

        noktaCheck.setBackground(new java.awt.Color(255, 255, 255));
        noktaCheck.setForeground(new java.awt.Color(0, 0, 0));
        noktaCheck.setText("nokta");
        noktaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noktaCheckActionPerformed(evt);
            }
        });

        nOrtaCheck.setBackground(new java.awt.Color(51, 102, 255));
        nOrtaCheck.setForeground(new java.awt.Color(0, 0, 0));
        nOrtaCheck.setText("orta");
        nOrtaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nOrtaCheckActionPerformed(evt);
            }
        });

        nKucukCheck.setBackground(new java.awt.Color(102, 153, 255));
        nKucukCheck.setForeground(new java.awt.Color(0, 0, 0));
        nKucukCheck.setText("küçük");
        nKucukCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nKucukCheckActionPerformed(evt);
            }
        });

        nBuyukCheck.setBackground(new java.awt.Color(102, 204, 255));
        nBuyukCheck.setForeground(new java.awt.Color(0, 0, 0));
        nBuyukCheck.setText("büyük");
        nBuyukCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nBuyukCheckActionPerformed(evt);
            }
        });

        cizgiCheck.setBackground(new java.awt.Color(0, 204, 51));
        cizgiCheck.setForeground(new java.awt.Color(0, 0, 204));
        cizgiCheck.setText("çizgi");
        cizgiCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cizgiCheckActionPerformed(evt);
            }
        });

        cInceCheck.setBackground(new java.awt.Color(153, 255, 0));
        cInceCheck.setForeground(new java.awt.Color(0, 0, 204));
        cInceCheck.setText("ince");
        cInceCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cInceCheckActionPerformed(evt);
            }
        });

        cOrtaCheck.setBackground(new java.awt.Color(102, 255, 51));
        cOrtaCheck.setForeground(new java.awt.Color(0, 0, 255));
        cOrtaCheck.setText("orta");
        cOrtaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cOrtaCheckActionPerformed(evt);
            }
        });

        cKalınCheck.setBackground(new java.awt.Color(51, 255, 51));
        cKalınCheck.setForeground(new java.awt.Color(0, 0, 204));
        cKalınCheck.setText("kalın");
        cKalınCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKalınCheckActionPerformed(evt);
            }
        });

        polyCheck.setBackground(new java.awt.Color(255, 255, 51));
        polyCheck.setForeground(new java.awt.Color(51, 51, 255));
        polyCheck.setText("poligon");
        polyCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polyCheckActionPerformed(evt);
            }
        });

        bosCheck.setBackground(new java.awt.Color(255, 255, 0));
        bosCheck.setForeground(new java.awt.Color(0, 0, 255));
        bosCheck.setText("içi boş");
        bosCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosCheckActionPerformed(evt);
            }
        });

        doluCheck.setBackground(new java.awt.Color(255, 255, 0));
        doluCheck.setForeground(new java.awt.Color(0, 0, 255));
        doluCheck.setText("içi dolu");
        doluCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doluCheckActionPerformed(evt);
            }
        });

        taraliCheck.setBackground(new java.awt.Color(255, 255, 0));
        taraliCheck.setForeground(new java.awt.Color(0, 0, 204));
        taraliCheck.setText("taralı");
        taraliCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taraliCheckActionPerformed(evt);
            }
        });

        ekleButton.setBackground(new java.awt.Color(51, 255, 255));
        ekleButton.setForeground(new java.awt.Color(255, 0, 51));
        ekleButton.setText("nokta ekle");
        ekleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButtonActionPerformed(evt);
            }
        });

        xCoordinate.setBackground(new java.awt.Color(255, 255, 255));

        yCoordinate.setBackground(new java.awt.Color(255, 255, 255));

        xCoordinateLabel.setText("x koordinatı");

        yCoordinateLabel.setText("y koordinatı");

        makeItHappenBoiii.setBackground(new java.awt.Color(0, 0, 204));
        makeItHappenBoiii.setForeground(new java.awt.Color(204, 51, 0));
        makeItHappenBoiii.setText("oluştur");
        makeItHappenBoiii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeItHappenBoiiiActionPerformed(evt);
            }
        });

        widthText.setBackground(new java.awt.Color(255, 255, 255));

        heightText.setBackground(new java.awt.Color(255, 255, 255));
        heightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTextActionPerformed(evt);
            }
        });

        jLabel1.setText("alan uzunluğu");

        jLabel2.setText("alan yüksekliği");

        cizButton.setBackground(new java.awt.Color(0, 153, 204));
        cizButton.setForeground(new java.awt.Color(255, 0, 0));
        cizButton.setText("çiz");
        cizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cizButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nKucukCheck)
                            .addComponent(nOrtaCheck)
                            .addComponent(nBuyukCheck)
                            .addComponent(noktaCheck))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cizgiCheck)
                            .addComponent(cInceCheck)
                            .addComponent(cOrtaCheck)
                            .addComponent(cKalınCheck))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(polyCheck)
                            .addComponent(bosCheck)
                            .addComponent(doluCheck)
                            .addComponent(taraliCheck)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(xCoordinateLabel)
                        .addGap(38, 38, 38)
                        .addComponent(yCoordinateLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ekleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cizButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(xCoordinate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yCoordinate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(widthText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(heightText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(makeItHappenBoiii))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeItHappenBoiii))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noktaCheck)
                    .addComponent(cizgiCheck)
                    .addComponent(polyCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nKucukCheck)
                    .addComponent(cInceCheck)
                    .addComponent(bosCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nOrtaCheck)
                    .addComponent(cOrtaCheck)
                    .addComponent(doluCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nBuyukCheck)
                    .addComponent(cKalınCheck)
                    .addComponent(taraliCheck))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yCoordinateLabel)
                    .addComponent(xCoordinateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xCoordinate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yCoordinate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ekleButton)
                    .addComponent(cizButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cKalınCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cKalınCheckActionPerformed
       if(cKalınCheck.isSelected()){
        xCoordinate.setVisible(true);
        yCoordinate.setVisible(true);
        xCoordinateLabel.setVisible(true);
        yCoordinateLabel.setVisible(true);
        cOrtaCheck.setSelected(false);
        cInceCheck.setSelected(false);
       }
       else{
        xCoordinate.setVisible(false);
        yCoordinate.setVisible(false);
        xCoordinateLabel.setVisible(false);
        yCoordinateLabel.setVisible(false);
       }
    }//GEN-LAST:event_cKalınCheckActionPerformed

    private void noktaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noktaCheckActionPerformed
        if(noktaCheck.isSelected()){
        nKucukCheck.setVisible(true);
        nOrtaCheck.setVisible(true);
        nBuyukCheck.setVisible(true);
        cizgiCheck.setEnabled(false);
        polyCheck.setEnabled(false);
        ekleButton.setEnabled(false);
        }
        else{
        nKucukCheck.setVisible(false);
        nOrtaCheck.setVisible(false);
        nBuyukCheck.setVisible(false);
        cizgiCheck.setEnabled(true);
        polyCheck.setEnabled(true);
        ekleButton.setEnabled(true);
        }
    }//GEN-LAST:event_noktaCheckActionPerformed

    private void cizgiCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cizgiCheckActionPerformed
        if(cizgiCheck.isSelected()){
        cInceCheck.setVisible(true);
        cOrtaCheck.setVisible(true);
        cKalınCheck.setVisible(true);
        noktaCheck.setEnabled(false);
        polyCheck.setEnabled(false);
        }
        else{
        cInceCheck.setVisible(false);
        cOrtaCheck.setVisible(false);
        cKalınCheck.setVisible(false);
        noktaCheck.setEnabled(true);
        polyCheck.setEnabled(true);
        }
    }//GEN-LAST:event_cizgiCheckActionPerformed

    private void polyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polyCheckActionPerformed
        if(polyCheck.isSelected()){
        bosCheck.setVisible(true);
        doluCheck.setVisible(true);
        taraliCheck.setVisible(true);
        noktaCheck.setEnabled(false);
        cizgiCheck.setEnabled(false);
        }
        else{
        bosCheck.setVisible(false);
        doluCheck.setVisible(false);
        taraliCheck.setVisible(false);
        noktaCheck.setEnabled(true);
        cizgiCheck.setEnabled(true);
        }
    }//GEN-LAST:event_polyCheckActionPerformed

    private void nKucukCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nKucukCheckActionPerformed
        if(nKucukCheck.isSelected()){
        xCoordinate.setVisible(true);
        yCoordinate.setVisible(true);
        xCoordinateLabel.setVisible(true);
        yCoordinateLabel.setVisible(true);
        nOrtaCheck.setSelected(false);
        nBuyukCheck.setSelected(false);
       }
       else{
        xCoordinate.setVisible(false);
        yCoordinate.setVisible(false);
        xCoordinateLabel.setVisible(false);
        yCoordinateLabel.setVisible(false);
       }
    }//GEN-LAST:event_nKucukCheckActionPerformed

    private void ekleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButtonActionPerformed
   
    
    
        int x = (Integer.valueOf(xCoordinate.getText()));
        int y = (Integer.valueOf(yCoordinate.getText()));
        xCoordinateList.add(x);
        yCoordinateList.add(y); 
    
    
    System.out.println("x koordinatları");
        for(int i = 0; i<xCoordinateList.size();i++){
            System.out.println(xCoordinateList.get(i));
        }
        System.out.println("y koordinatları");
        for(int i = 0; i<yCoordinateList.size();i++){
            System.out.println(yCoordinateList.get(i));
        }
    }//GEN-LAST:event_ekleButtonActionPerformed

    private void makeItHappenBoiiiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeItHappenBoiiiActionPerformed
        int width = Integer.valueOf(widthText.getText());
        int height = Integer.valueOf(heightText.getText());
        d.setSize(width, height);
        d.setVisible(true);
    }//GEN-LAST:event_makeItHappenBoiiiActionPerformed

    private void heightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightTextActionPerformed

    private void nOrtaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nOrtaCheckActionPerformed
       if(nOrtaCheck.isSelected()){
        xCoordinate.setVisible(true);
        yCoordinate.setVisible(true);
        xCoordinateLabel.setVisible(true);
        yCoordinateLabel.setVisible(true);
        nKucukCheck.setSelected(false);
        nBuyukCheck.setSelected(false);
       }
       else{
        xCoordinate.setVisible(false);
        yCoordinate.setVisible(false);
        xCoordinateLabel.setVisible(false);
        yCoordinateLabel.setVisible(false);
       }
    }//GEN-LAST:event_nOrtaCheckActionPerformed

    private void nBuyukCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBuyukCheckActionPerformed
        if(nBuyukCheck.isSelected()){
        xCoordinate.setVisible(true);
        yCoordinate.setVisible(true);
        xCoordinateLabel.setVisible(true);
        yCoordinateLabel.setVisible(true);
        nOrtaCheck.setSelected(false);
        nKucukCheck.setSelected(false);
       }
       else{
        xCoordinate.setVisible(false);
        yCoordinate.setVisible(false);
        xCoordinateLabel.setVisible(false);
        yCoordinateLabel.setVisible(false);
       }
    }//GEN-LAST:event_nBuyukCheckActionPerformed

    private void cInceCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cInceCheckActionPerformed
        if(cInceCheck.isSelected()){
        xCoordinate.setVisible(true);
        yCoordinate.setVisible(true);
        xCoordinateLabel.setVisible(true);
        yCoordinateLabel.setVisible(true);
        cOrtaCheck.setSelected(false);
        cKalınCheck.setSelected(false);
       }
       else{
        xCoordinate.setVisible(false);
        yCoordinate.setVisible(false);
        xCoordinateLabel.setVisible(false);
        yCoordinateLabel.setVisible(false);
       }
    }//GEN-LAST:event_cInceCheckActionPerformed

    private void cOrtaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cOrtaCheckActionPerformed
        if(cOrtaCheck.isSelected()){
        xCoordinate.setVisible(true);
        yCoordinate.setVisible(true);
        xCoordinateLabel.setVisible(true);
        yCoordinateLabel.setVisible(true);
        cInceCheck.setSelected(false);
        cKalınCheck.setSelected(false);
       }
       else{
        xCoordinate.setVisible(false);
        yCoordinate.setVisible(false);
        xCoordinateLabel.setVisible(false);
        yCoordinateLabel.setVisible(false);
       }
    }//GEN-LAST:event_cOrtaCheckActionPerformed

    private void bosCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosCheckActionPerformed
        if(bosCheck.isSelected()){
        xCoordinate.setVisible(true);
        yCoordinate.setVisible(true);
        xCoordinateLabel.setVisible(true);
        yCoordinateLabel.setVisible(true);
        doluCheck.setSelected(false);
        taraliCheck.setSelected(false);
       }
       else{
        xCoordinate.setVisible(false);
        yCoordinate.setVisible(false);
        xCoordinateLabel.setVisible(false);
        yCoordinateLabel.setVisible(false);
       }
    }//GEN-LAST:event_bosCheckActionPerformed

    private void doluCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doluCheckActionPerformed
        if(doluCheck.isSelected()){
        xCoordinate.setVisible(true);
        yCoordinate.setVisible(true);
        xCoordinateLabel.setVisible(true);
        yCoordinateLabel.setVisible(true);
        bosCheck.setSelected(false);
        taraliCheck.setSelected(false);
       }
       else{
        xCoordinate.setVisible(false);
        yCoordinate.setVisible(false);
        xCoordinateLabel.setVisible(false);
        yCoordinateLabel.setVisible(false);
       }
    }//GEN-LAST:event_doluCheckActionPerformed

    private void taraliCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taraliCheckActionPerformed
        if(taraliCheck.isSelected()){
        xCoordinate.setVisible(true);
        yCoordinate.setVisible(true);
        xCoordinateLabel.setVisible(true);
        yCoordinateLabel.setVisible(true);
        bosCheck.setSelected(false);
        doluCheck.setSelected(false);
       }
       else{
        xCoordinate.setVisible(false);
        yCoordinate.setVisible(false);
        xCoordinateLabel.setVisible(false);
        yCoordinateLabel.setVisible(false);
       }
    }//GEN-LAST:event_taraliCheckActionPerformed

    public static int[] arrayListToList(List<Integer> arrayList) {
        int[] list = new int[arrayList.size()];
        for (int i = 0; i < list.length; i++) {
            list[i] = arrayList.get(i).intValue();
        }
        return list;
    }
    private void cizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cizButtonActionPerformed
         
        Graphics g = d.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        int[] xList = arrayListToList(xCoordinateList);
        int[] yList = arrayListToList(yCoordinateList);
        
        if(nKucukCheck.isSelected()){
            
            int xC = Integer.parseInt(xCoordinate.getText());
            int yC = Integer.parseInt(yCoordinate.getText());
            d.drawDot(g2, xC, yC, 5, 5, 1);
        }
        else if(nOrtaCheck.isSelected()){
            
            int xC = Integer.parseInt(xCoordinate.getText());
            int yC = Integer.parseInt(yCoordinate.getText());
            d.drawDot(g2, xC, yC, 10, 10, 3);
        }
        else if(nBuyukCheck.isSelected()){
            
            int xC = Integer.parseInt(xCoordinate.getText());
            int yC = Integer.parseInt(yCoordinate.getText());
            d.drawDot(g2, xC, yC, 20, 20, 3);
        }
        else if(cInceCheck.isSelected()){
            
            d.drawLine(g2, xList, yList, 1);
            
        }
        else if(cOrtaCheck.isSelected()){
            
            d.drawLine(g2, xList, yList, 3);
            
        }
        else if(cKalınCheck.isSelected()){
            
            d.drawLine(g2, xList, yList, 7);
            
        }
        else if(bosCheck.isSelected()){
            d.drawBosPolygon(g2, xList, yList);
        }
        else if(doluCheck.isSelected()){
            d.drawDoluPolygon(g2, xList, yList);
        }
        else if(taraliCheck.isSelected()){
            d.drawTaraliPolygon(g2, xList, yList);
        }
        xCoordinateList.clear();
        yCoordinateList.clear();
        
        
    }//GEN-LAST:event_cizButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shapeMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shapeMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shapeMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shapeMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shapeMaker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bosCheck;
    private javax.swing.JCheckBox cInceCheck;
    private javax.swing.JCheckBox cKalınCheck;
    private javax.swing.JCheckBox cOrtaCheck;
    private javax.swing.JButton cizButton;
    private javax.swing.JCheckBox cizgiCheck;
    private javax.swing.JCheckBox doluCheck;
    private javax.swing.JButton ekleButton;
    private javax.swing.JTextField heightText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton makeItHappenBoiii;
    private javax.swing.JCheckBox nBuyukCheck;
    private javax.swing.JCheckBox nKucukCheck;
    private javax.swing.JCheckBox nOrtaCheck;
    private javax.swing.JCheckBox noktaCheck;
    private javax.swing.JCheckBox polyCheck;
    private javax.swing.JCheckBox taraliCheck;
    private javax.swing.JTextField widthText;
    private javax.swing.JTextField xCoordinate;
    private javax.swing.JLabel xCoordinateLabel;
    private javax.swing.JTextField yCoordinate;
    private javax.swing.JLabel yCoordinateLabel;
    // End of variables declaration//GEN-END:variables
}
