/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cbsquiz;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;

/**
 *
 * @author emirh
 */
public class drawings extends javax.swing.JFrame {
    
    
    /**
     * Creates new form drawings
     */
    
    
   
    
    public drawings() {
        initComponents();
        jPanel1.setBackground(Color.black);
        this.setResizable(false);
        
    }
   

public void paint(Graphics2D g2) {

  g2.setBackground(Color.black);
  g2.setColor(Color.YELLOW);
}

public void bruh(Graphics2D g2){
    g2.drawRect(150, 150, 100, 100);
}

    public void drawDot(Graphics2D g2,int x,int y,int width,int height,int thickness){
        g2.setStroke(new BasicStroke(thickness));
        
        g2.setPaint(Color.yellow);
        g2.fillOval(x, y, width, height);
        
        
    }
    public void drawBosPolygon(Graphics2D g2, int[] xValues, int[] yValues){
        int dots = xValues.length;
        g2.setPaint(Color.yellow);
        g2.setStroke(new BasicStroke(3));
        g2.drawPolygon(xValues, yValues, dots);
        
    }
    public void drawDoluPolygon(Graphics2D g2, int[] xValues, int[] yValues){
        int dots = xValues.length;
        g2.setPaint(Color.yellow);
        g2.setStroke(new BasicStroke(3));
        g2.fillPolygon(xValues, yValues, dots);
    }
    public void drawTaraliPolygon(Graphics2D g2, int[] xValues, int[] yValues){
        int dots = xValues.length;
        g2.setPaint(Color.yellow);
        float[] dashPattern = { 30, 10, 10, 10 };
        g2.setStroke(new BasicStroke(8, BasicStroke.CAP_BUTT,
                 BasicStroke.JOIN_MITER, 10,
                 dashPattern, 0));
        g2.drawPolygon(xValues, yValues, dots);
    }
    public void drawLine(Graphics2D g2, int[] xValues,int[] yValues, int thickness){
        g2.setPaint(Color.yellow);
        for(int i = 0; i<xValues.length -1; i++){
            g2.setStroke(new BasicStroke(thickness));
            g2.drawLine(xValues[i], yValues[i], xValues[i+1], yValues[i+1]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(drawings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(drawings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(drawings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(drawings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new drawings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
